# Generated by Django 5.1.14 on 2025-11-11 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Nombre del cultivo')),
                ('city', models.CharField(max_length=80, verbose_name='Ciudad')),
                ('country_code', models.CharField(default='SV', max_length=2, verbose_name='País (ISO2)')),
                ('sowing_date', models.DateField(blank=True, null=True, verbose_name='Fecha de siembra')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
            ],
            options={
                'verbose_name': 'Cultivo',
                'verbose_name_plural': 'Cultivos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WeatherRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('rain_mm', models.FloatField(blank=True, null=True)),
                ('wind_ms', models.FloatField(blank=True, null=True)),
                ('recommendation', models.TextField(blank=True, default='')),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='monitor.crop')),
            ],
            options={
                'verbose_name': 'Registro Climático',
                'verbose_name_plural': 'Registros Climáticos',
                'ordering': ['-timestamp'],
            },
        ),
    ]
