# Generated by Django 5.1.14 on 2025-11-18 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_customuser_bio_customuser_display_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('irrigation', 'Riego'), ('fertilizer', 'Fertilizante'), ('pest', 'Plaga / Enfermedad'), ('general', 'General')], default='general', max_length=32)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notified', models.BooleanField(default=False)),
                ('resolved', models.BooleanField(default=False)),
                ('user_response', models.CharField(blank=True, default='', max_length=64)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='monitor.crop')),
            ],
            options={
                'verbose_name': 'Alerta de Cultivo',
                'verbose_name_plural': 'Alertas de Cultivo',
                'ordering': ['-created_at'],
            },
        ),
    ]
