# Generated by Django 5.2.8 on 2025-11-18 23:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0006_cropalert'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbonoApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_applied', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de aplicación')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notas')),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abono_applications', to='monitor.crop')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abono_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aplicación de Abono',
                'verbose_name_plural': 'Aplicaciones de Abono',
                'ordering': ['-date_applied'],
            },
        ),
    ]
