# Generated by Django 5.1.14 on 2025-11-19 04:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0007_abonoapplication'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abonoapplication',
            options={'ordering': ['-scheduled_date', '-date_applied'], 'verbose_name': 'Aplicación de Abono', 'verbose_name_plural': 'Aplicaciones de Abono'},
        ),
        migrations.AddField(
            model_name='abonoapplication',
            name='scheduled_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha programada'),
        ),
        migrations.AddField(
            model_name='abonoapplication',
            name='status',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aplicado', 'Aplicado'), ('no_aplicado', 'No Aplicado')], default='pendiente', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='abonoapplication',
            name='date_applied',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de aplicación'),
        ),
    ]
