# Generated by Django 5.1.14 on 2025-11-19 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0008_alter_abonoapplication_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonoapplication',
            name='tip',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Tip de abono'),
        ),
    ]
